"""Freeze isolated long-range Train/Dev/Holdout scene splits for GAT rescue.

The full dynamic tracks are retained in one immutable JSON file per scene.
Compact split manifests index those files, avoiding a multi-gigabyte in-memory
monolithic JSON object while preserving the existing scene-entry schema.
Formal V2 is deliberately not generated by this script.
"""

from __future__ import annotations

import argparse
import csv
from datetime import datetime
import hashlib
import json
from pathlib import Path
import sys
from typing import Any, Mapping, Sequence

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from planning.semi_structured_long_range_benchmark import (  # noqa: E402
    APPLICATION_SETTING,
    DT,
    FAMILY_ORDER,
    LONG_RANGE_MAX_STEPS,
    MISSION_DISTANCE_RANGE_M,
    OPERATIONAL_FLIGHT_BAND_M,
    SENSOR_DIRECTION_COUNT,
    SENSOR_RANGE_M,
    STAGE_ORDER,
    STAGE_POPULATION,
    STATIC_DYNAMIC_RATIO,
    TASK_PATTERNS,
    WORKSPACE_BOUNDS,
    generate_scenario_entry,
    json_ready,
    stable_hash,
)


DEFAULT_ARTIFACT = (
    REPO_ROOT
    / "artifacts/gat_recurrent_smoothness_rescue/20260821_180244"
)
HISTORICAL_REGISTRY = (
    REPO_ROOT
    / "artifacts/semi_structured_long_range_main_benchmark/20260820_193228"
    / "11_formal_manifest/ALL_USED_SCENE_REGISTRY.csv"
)
SPLITS = {
    "training": {
        "counts_per_stage": 250,
        "seed_base": 3_100_000_000,
        "prefix": "GATRS_TRAIN_",
        "directory": "02_recurrent_dataset",
        "scene_directory": "train_scenes",
        "manifest": "GAT_RS_TRAIN_SCENE_MANIFEST.json",
    },
    "development": {
        "counts_per_stage": 100,
        "seed_base": 3_200_000_000,
        "prefix": "GATRS_DEV_",
        "directory": "07_development",
        "scene_directory": "dev_scenes",
        "manifest": "GAT_RS_DEV_SCENE_MANIFEST.json",
    },
    "holdout": {
        "counts_per_stage": 100,
        "seed_base": 3_300_000_000,
        "prefix": "GATRS_HOLDOUT_",
        "directory": "08_holdout",
        "scene_directory": "holdout_scenes",
        "manifest": "GAT_RS_HOLDOUT_SCENE_MANIFEST.json",
    },
}
FINGERPRINT_FIELDS = (
    "seed",
    "geometry_fingerprint",
    "dynamic_track_fingerprint",
    "translation_invariant_fingerprint",
    "start_goal_fingerprint",
)
REGISTRY_FIELDS = (
    "scene_id",
    "split",
    "source",
    *FINGERPRINT_FIELDS,
)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_json(path: Path, value: Any, *, compact: bool = True) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    separators = (",", ":") if compact else None
    temporary.write_text(
        json.dumps(
            json_ready(value),
            ensure_ascii=False,
            sort_keys=False,
            separators=separators,
            indent=None if compact else 2,
        )
        + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def read_registry(path: Path) -> list[dict[str, Any]]:
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def atomic_csv(
    path: Path, fields: Sequence[str], rows: Sequence[Mapping[str, Any]]
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    temporary.replace(path)


def start_goal_fingerprint(entry: Mapping[str, Any]) -> str:
    return stable_hash({"starts": entry["starts"], "goals": entry["goals"]})


def normalized_registry_row(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "scene_id": row.get("scene_id", ""),
        "split": row.get("split", "historical"),
        "source": row.get("source", ""),
        "seed": row.get("seed", ""),
        "geometry_fingerprint": row.get("geometry_fingerprint", ""),
        "dynamic_track_fingerprint": row.get("dynamic_track_fingerprint", ""),
        "translation_invariant_fingerprint": row.get(
            "translation_invariant_fingerprint", ""
        ),
        "start_goal_fingerprint": row.get("start_goal_fingerprint", ""),
    }


def registry_sets(rows: Sequence[Mapping[str, Any]]) -> dict[str, set[Any]]:
    result: dict[str, set[Any]] = {name: set() for name in FINGERPRINT_FIELDS}
    for row in rows:
        for name in FINGERPRINT_FIELDS:
            value: Any = row.get(name)
            if value in (None, ""):
                continue
            if name == "seed":
                value = int(value)
            result[name].add(value)
    return result


def scene_values(entry: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "seed": int(entry["seed"]),
        "geometry_fingerprint": str(entry["geometry_fingerprint"]),
        "dynamic_track_fingerprint": str(entry["dynamic_track_fingerprint"]),
        "translation_invariant_fingerprint": str(
            entry["translation_invariant_fingerprint"]
        ),
        "start_goal_fingerprint": start_goal_fingerprint(entry),
    }


def validate_entry(entry: Mapping[str, Any]) -> list[str]:
    errors: list[str] = []
    stage = str(entry["stage"])
    target = STAGE_POPULATION[stage]
    if len(entry["static_obstacles"]) != int(target["static"]):
        errors.append("static_population")
    if len(entry["dynamic_obstacles"]) != int(target["dynamic"]):
        errors.append("dynamic_population")
    distances = np.asarray(entry["mission"]["straight_line_distances_m"], dtype=float)
    if np.any(distances < MISSION_DISTANCE_RANGE_M[0]) or np.any(
        distances > MISSION_DISTANCE_RANGE_M[1]
    ):
        errors.append("mission_distance")
    if not bool(entry["static_route_witness_evaluation_only"]["all_agents_feasible"]):
        errors.append("static_route_witness")
    if any(
        len(track) != LONG_RANGE_MAX_STEPS + 1
        for track in entry["dynamic_obstacle_trajectories"]
    ):
        errors.append("dynamic_track_length")
    if entry["boundary_mode"] != "closed_workspace_with_floor_and_ceiling":
        errors.append("boundary_mode")
    return errors


def compact_scene_index(
    entry: Mapping[str, Any], scene_relative: str, scene_sha256: str
) -> dict[str, Any]:
    values = scene_values(entry)
    return {
        "scenario_id": entry["scenario_id"],
        "scenario_file": scene_relative,
        "scenario_file_sha256": scene_sha256,
        "stage": entry["stage"],
        "family": entry["family"],
        "task_pattern": entry["task_pattern"],
        **values,
        "mission_distance_min_m": entry["mission"][
            "straight_line_distance_min_m"
        ],
        "mission_distance_mean_m": entry["mission"][
            "straight_line_distance_mean_m"
        ],
        "mission_distance_max_m": entry["mission"][
            "straight_line_distance_max_m"
        ],
        "static_obstacle_count": len(entry["static_obstacles"]),
        "dynamic_obstacle_count": len(entry["dynamic_obstacles"]),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact-root", type=Path, default=DEFAULT_ARTIFACT)
    parser.add_argument(
        "--historical-registry", type=Path, default=HISTORICAL_REGISTRY
    )
    args = parser.parse_args()
    root = args.artifact_root.resolve()
    historical_registry = args.historical_registry.resolve()
    if not historical_registry.is_file():
        raise FileNotFoundError(historical_registry)

    for directory in (
        "00_context",
        "01_smoothness_metric_audit",
        "02_recurrent_dataset",
        "03_counterfactual_rollouts",
        "04_feature_alignment",
        "05_gat_r_training",
        "06_gat_rs_training",
        "07_development",
        "08_holdout",
        "09_final_freeze",
        "10_formal_v2",
        "11_statistics",
        "12_paper_ready",
    ):
        (root / directory).mkdir(parents=True, exist_ok=True)

    historical_rows = [
        normalized_registry_row(row) for row in read_registry(historical_registry)
    ]
    seen = registry_sets(historical_rows)
    registry_rows = list(historical_rows)
    split_sets: dict[str, dict[str, set[Any]]] = {}
    split_summaries: dict[str, Any] = {}

    for split, spec in SPLITS.items():
        output_dir = root / str(spec["directory"])
        scene_dir = output_dir / str(spec["scene_directory"])
        manifest_path = output_dir / str(spec["manifest"])
        if manifest_path.exists() or scene_dir.exists():
            raise RuntimeError(
                f"refusing to overwrite an existing frozen split: {manifest_path}"
            )
        scene_dir.mkdir(parents=True)
        counts_per_stage = int(spec["counts_per_stage"])
        seed_base = int(spec["seed_base"])
        expected = counts_per_stage * len(STAGE_ORDER)
        print(
            f"[gat-rescue-split] generating {split}: {expected} scenes",
            flush=True,
        )
        entries: list[dict[str, Any]] = []
        current: dict[str, set[Any]] = {
            name: set() for name in FINGERPRINT_FIELDS
        }
        overlap = {name: 0 for name in FINGERPRINT_FIELDS}
        validation_errors: list[dict[str, Any]] = []

        generated = 0
        for stage_index, stage in enumerate(STAGE_ORDER):
            for scenario_index in range(counts_per_stage):
                seed = seed_base + stage_index * 100_000 + scenario_index
                if seed > np.iinfo(np.uint32).max:
                    raise RuntimeError(f"seed is outside uint32: {seed}")
                entry = generate_scenario_entry(
                    stage=stage,
                    scenario_index=scenario_index,
                    seed=seed,
                    prefix=str(spec["prefix"]),
                )
                errors = validate_entry(entry)
                if errors:
                    validation_errors.append(
                        {"scenario_id": entry["scenario_id"], "errors": errors}
                    )
                    continue
                values = scene_values(entry)
                duplicates = {
                    name: values[name] in current[name] for name in FINGERPRINT_FIELDS
                }
                if any(duplicates.values()):
                    raise RuntimeError(
                        f"internal duplicate in {split}/{entry['scenario_id']}: {duplicates}"
                    )
                prior = {
                    name: values[name] in seen[name] for name in FINGERPRINT_FIELDS
                }
                for name, present in prior.items():
                    overlap[name] += int(present)
                if any(prior.values()):
                    raise RuntimeError(
                        f"historical/new-split overlap in {split}/{entry['scenario_id']}: {prior}"
                    )

                scene_path = scene_dir / f"{entry['scenario_id']}.json"
                atomic_json(scene_path, entry)
                scene_relative = str(scene_path.relative_to(root)).replace("\\", "/")
                file_sha = sha256_file(scene_path)
                entries.append(compact_scene_index(entry, scene_relative, file_sha))
                registry_rows.append(
                    {
                        "scene_id": entry["scenario_id"],
                        "split": split,
                        "source": scene_relative,
                        **values,
                    }
                )
                for name in FINGERPRINT_FIELDS:
                    current[name].add(values[name])
                    seen[name].add(values[name])
                generated += 1
                if generated % 25 == 0 or generated == expected:
                    print(
                        f"[gat-rescue-split] {split}: {generated}/{expected}",
                        flush=True,
                    )

        family_counts = {
            stage: {
                family: sum(
                    row["stage"] == stage and row["family"] == family
                    for row in entries
                )
                for family in FAMILY_ORDER
            }
            for stage in STAGE_ORDER
        }
        task_counts = {
            task: sum(row["task_pattern"] == task for row in entries)
            for task in TASK_PATTERNS
        }
        stage_counts = {
            stage: sum(row["stage"] == stage for row in entries)
            for stage in STAGE_ORDER
        }
        if generated != expected or validation_errors:
            raise RuntimeError(
                f"{split} generation incomplete: generated={generated}, expected={expected}, "
                f"errors={validation_errors[:3]}"
            )
        if any(value != counts_per_stage for value in stage_counts.values()):
            raise RuntimeError(f"{split} stage imbalance: {stage_counts}")
        expected_family = counts_per_stage // len(FAMILY_ORDER)
        if any(
            value != expected_family
            for per_stage in family_counts.values()
            for value in per_stage.values()
        ):
            raise RuntimeError(f"{split} family imbalance: {family_counts}")

        compact_manifest = {
            "schema_version": "gat_recurrent_scene_file_manifest_v1",
            "application_setting": APPLICATION_SETTING,
            "split": split,
            "created_at": datetime.now().astimezone().isoformat(),
            "workspace_bounds": json_ready(WORKSPACE_BOUNDS),
            "operational_flight_band_m": json_ready(OPERATIONAL_FLIGHT_BAND_M),
            "mission_distance_range_m": json_ready(MISSION_DISTANCE_RANGE_M),
            "sensor_direction_count": SENSOR_DIRECTION_COUNT,
            "gat_canonical_sector_count": 56,
            "sensor_range_m": SENSOR_RANGE_M,
            "dt": DT,
            "max_steps": LONG_RANGE_MAX_STEPS,
            "stage_order": list(STAGE_ORDER),
            "stage_population": json_ready(STAGE_POPULATION),
            "static_dynamic_ratio": STATIC_DYNAMIC_RATIO,
            "family_order": list(FAMILY_ORDER),
            "task_patterns": list(TASK_PATTERNS),
            "counts_per_stage": counts_per_stage,
            "unique_scenario_count": generated,
            "seed_base": seed_base,
            "materialization_contract": (
                "load each scenario_file as one full "
                "semi_structured_long_range_scene_v1 entry"
            ),
            "entries": entries,
        }
        compact_manifest["manifest_semantic_sha256"] = stable_hash(
            {
                key: value
                for key, value in compact_manifest.items()
                if key not in {"created_at", "entries"}
            }
            | {
                "entry_identities": [
                    {
                        "scenario_id": row["scenario_id"],
                        "scenario_file_sha256": row["scenario_file_sha256"],
                        **{
                            name: row[name] for name in FINGERPRINT_FIELDS
                        },
                    }
                    for row in entries
                ]
            }
        )
        atomic_json(manifest_path, compact_manifest, compact=False)
        manifest_file_sha = sha256_file(manifest_path)
        validation = {
            "schema_version": "gat_recurrent_split_validation_v1",
            "status": "PASS",
            "split": split,
            "scenario_count": generated,
            "stage_counts": stage_counts,
            "family_counts_by_stage": family_counts,
            "task_pattern_counts": task_counts,
            "internal_duplicates": {
                name: generated - len(current[name]) for name in FINGERPRINT_FIELDS
            },
            "overlap_with_historical_and_earlier_new_splits": overlap,
            "full_scene_file_count": len(list(scene_dir.glob("*.json"))),
            "manifest_semantic_sha256": compact_manifest[
                "manifest_semantic_sha256"
            ],
            "manifest_file_sha256": manifest_file_sha,
            "formal_v2_generated": False,
            "performance_result_count_at_freeze": 0,
        }
        atomic_json(
            manifest_path.with_name(manifest_path.stem + "_validation.json"),
            validation,
            compact=False,
        )
        split_sets[split] = current
        split_summaries[split] = {
            "scenario_count": generated,
            "counts_per_stage": counts_per_stage,
            "seed_base": seed_base,
            "manifest": str(manifest_path.relative_to(root)).replace("\\", "/"),
            "manifest_semantic_sha256": compact_manifest[
                "manifest_semantic_sha256"
            ],
            "manifest_file_sha256": manifest_file_sha,
        }
        print(f"[gat-rescue-split] {split}: PASS", flush=True)

    pairwise: dict[str, dict[str, int]] = {}
    names = list(split_sets)
    for left_index, left in enumerate(names):
        for right in names[left_index + 1 :]:
            pairwise[f"{left}__{right}"] = {
                name: len(split_sets[left][name] & split_sets[right][name])
                for name in FINGERPRINT_FIELDS
            }
    if any(any(values.values()) for values in pairwise.values()):
        raise RuntimeError(f"new split pairwise overlap: {pairwise}")

    registry_path = root / "02_recurrent_dataset/ALL_USED_SCENE_REGISTRY.csv"
    atomic_csv(registry_path, REGISTRY_FIELDS, registry_rows)
    registry_sha = sha256_file(registry_path)
    freeze = {
        "schema_version": "gat_recurrent_rescue_split_freeze_v1",
        "status": "PASS",
        "created_at": datetime.now().astimezone().isoformat(),
        "historical_registry_source": str(
            historical_registry.relative_to(REPO_ROOT)
        ).replace("\\", "/"),
        "historical_registry_sha256": sha256_file(historical_registry),
        "historical_scene_row_count": len(historical_rows),
        "new_splits": split_summaries,
        "pairwise_new_split_overlap": pairwise,
        "isolation_dimensions": list(FINGERPRINT_FIELDS),
        "combined_registry": str(registry_path.relative_to(root)).replace(
            "\\", "/"
        ),
        "combined_registry_sha256": registry_sha,
        "formal_v2": {
            "generated": False,
            "reserved_seed_base": 3_400_000_000,
            "reserved_counts_per_stage": 100,
            "performance_previewed": False,
            "creation_gate": "HOLDOUT_GAT_RS_GT_FP_AND_COLLISION_LE_FP",
        },
        "old_formal_v1_usage": "ISOLATION_METADATA_ONLY",
    }
    atomic_json(
        root / "02_recurrent_dataset/dataset_split_freeze.json",
        freeze,
        compact=False,
    )
    atomic_json(
        root / "00_context/FORMAL_V2_NOT_GENERATED.json",
        {
            "status": "NOT_GENERATED",
            "reason": "strict Dev then Holdout hard-gate ordering",
            "reserved_seed_base": 3_400_000_000,
            "formal_v2_scenario_count_if_authorized": 400,
            "formal_v2_episode_count": 0,
            "formal_v2_data_used_for_training_or_selection": False,
        },
        compact=False,
    )
    print(
        json.dumps(
            {
                "status": "PASS",
                "counts": {
                    name: value["scenario_count"]
                    for name, value in split_summaries.items()
                },
                "formal_v2_generated": False,
            }
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()
