
"""
Known-goal fast local FMM-like guiding sequence generator.

This version is NOT an RL module.

Assumption:
    - Current local LiDAR observation is available.
    - The local target position is known.
    - We generate a guiding waypoint sequence directly in the local frame.
    - The sequence is generated by virtual rollout; it does not mean the robot has actually moved.

Pipeline:
    Current simulated LiDAR observation
        -> sector probability threat field
        -> low-resolution 2D local FMM-like arrival-time field T(x, y)
        -> risk-aware top-k sector candidate directions
        -> one-shot virtual waypoint sequence generation toward the known target

Dependencies:
    pip install numpy matplotlib
"""

import heapq
import time
from dataclasses import dataclass
from typing import Tuple, List

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# 1. Utilities
# ============================================================

def normalize(v: np.ndarray, eps: float = 1e-8) -> np.ndarray:
    v = np.asarray(v, dtype=float)
    n = np.linalg.norm(v)
    if n < eps:
        return np.zeros_like(v)
    return v / n


def cartesian_to_spherical(points: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    points = np.asarray(points, dtype=float)
    x, y, z = points[:, 0], points[:, 1], points[:, 2]

    r = np.linalg.norm(points, axis=1)
    theta = np.arctan2(y, x)
    phi = np.arctan2(z, np.sqrt(x ** 2 + y ** 2))

    return r, theta, phi


def spherical_dir(theta: float, phi: float) -> np.ndarray:
    return np.array([
        np.cos(phi) * np.cos(theta),
        np.cos(phi) * np.sin(theta),
        np.sin(phi),
    ], dtype=float)


def generate_cylinder_surface_points(
    center: np.ndarray,
    radius: float,
    height: float,
    n_theta: int = 180,
    n_z: int = 90,
) -> np.ndarray:
    """
    Generate simulated current LiDAR observation points on a cylinder surface.

    The guidance generator only receives this point cloud, not the cylinder model.
    """
    cx, cy, cz = center

    theta = np.linspace(0, 2 * np.pi, n_theta)
    z = np.linspace(cz - height / 2, cz + height / 2, n_z)
    theta_grid, z_grid = np.meshgrid(theta, z)

    x = cx + radius * np.cos(theta_grid)
    y = cy + radius * np.sin(theta_grid)

    return np.stack([x.ravel(), y.ravel(), z_grid.ravel()], axis=1)


# ============================================================
# 2. Sector probability threat field
# ============================================================

@dataclass
class SectorThreatConfig:
    n_theta: int = 36
    n_phi: int = 13
    r_max: float = 8.0

    lidar_phi_min: float = np.deg2rad(-45)
    lidar_phi_max: float = np.deg2rad(45)

    r_safe: float = 0.45
    sigma_d: float = 0.9
    sigma_r: float = 0.5
    density_alpha: float = 0.06

    # Conservative risk behind an observed obstacle in the same sector.
    rho_occl: float = 0.6


class SectorThreatField:
    """
    Sector-based local probability risk field.

    It only uses the current local LiDAR points.
    No global map, no obstacle model, no RL.
    """

    def __init__(self, cfg: SectorThreatConfig = SectorThreatConfig()):
        self.cfg = cfg

        self.theta_min = -np.pi
        self.theta_max = np.pi
        self.phi_min = -np.pi / 2
        self.phi_max = np.pi / 2

        self.dtheta = (self.theta_max - self.theta_min) / cfg.n_theta
        self.dphi = (self.phi_max - self.phi_min) / cfg.n_phi

        self.d_min = np.full((cfg.n_theta, cfg.n_phi), cfg.r_max, dtype=float)
        self.count = np.zeros((cfg.n_theta, cfg.n_phi), dtype=float)
        self.p_dist = np.zeros((cfg.n_theta, cfg.n_phi), dtype=float)
        self.p_dens = np.zeros((cfg.n_theta, cfg.n_phi), dtype=float)
        self.p_threat = np.zeros((cfg.n_theta, cfg.n_phi), dtype=float)

        self.sector_dirs = self._build_sector_dirs()

    def _build_sector_dirs(self) -> np.ndarray:
        dirs = np.zeros((self.cfg.n_theta, self.cfg.n_phi, 3), dtype=float)

        for a in range(self.cfg.n_theta):
            theta_c = self.theta_min + (a + 0.5) * self.dtheta
            for b in range(self.cfg.n_phi):
                phi_c = self.phi_min + (b + 0.5) * self.dphi
                dirs[a, b] = spherical_dir(theta_c, phi_c)

        return dirs

    def _sector_index(self, theta, phi):
        a = np.floor((theta - self.theta_min) / self.dtheta).astype(int)
        b = np.floor((phi - self.phi_min) / self.dphi).astype(int)

        a = np.clip(a, 0, self.cfg.n_theta - 1)
        b = np.clip(b, 0, self.cfg.n_phi - 1)

        return a, b

    def build_from_lidar_points(self, lidar_points: np.ndarray) -> None:
        lidar_points = np.asarray(lidar_points, dtype=float)

        self.d_min.fill(self.cfg.r_max)
        self.count.fill(0.0)
        self.p_dist.fill(0.0)
        self.p_dens.fill(0.0)
        self.p_threat.fill(0.0)

        if len(lidar_points) == 0:
            return

        r, theta, phi = cartesian_to_spherical(lidar_points)

        valid = (
            (r > 1e-6)
            & (r <= self.cfg.r_max)
            & (phi >= self.cfg.lidar_phi_min)
            & (phi <= self.cfg.lidar_phi_max)
        )

        if not np.any(valid):
            return

        a_idx, b_idx = self._sector_index(theta[valid], phi[valid])
        np.add.at(self.count, (a_idx, b_idx), 1.0)
        np.minimum.at(self.d_min, (a_idx, b_idx), r[valid])

        has_obs = self.count > 0

        dist_excess = self.d_min - self.cfg.r_safe
        self.p_dist[has_obs] = np.where(
            self.d_min[has_obs] <= self.cfg.r_safe,
            1.0,
            np.exp(-dist_excess[has_obs] / self.cfg.sigma_d),
        )

        self.p_dens = 1.0 - np.exp(-self.cfg.density_alpha * self.count)

        self.p_threat = 1.0 - (1.0 - self.p_dist) * (1.0 - self.p_dens)
        self.p_threat = np.clip(self.p_threat, 0.0, 1.0)

    def query_risk_many(self, points: np.ndarray) -> np.ndarray:
        points = np.asarray(points, dtype=float)
        if points.ndim == 1:
            points = points[None, :]

        r = np.linalg.norm(points, axis=1)
        risks = np.zeros(len(points), dtype=float)

        valid = r >= 1e-6
        if not np.any(valid):
            return risks

        pv = points[valid]
        rv = r[valid]

        theta = np.arctan2(pv[:, 1], pv[:, 0])
        phi = np.arctan2(pv[:, 2], np.sqrt(pv[:, 0] ** 2 + pv[:, 1] ** 2))

        a, b = self._sector_index(theta, phi)
        has_obs = self.count[a, b] > 0

        local_risk = np.zeros(len(pv), dtype=float)

        if np.any(has_obs):
            ah = a[has_obs]
            bh = b[has_obs]
            rh = rv[has_obs]

            d_obs = self.d_min[ah, bh]
            p_th = self.p_threat[ah, bh]

            radial = p_th * np.exp(-0.5 * ((rh - d_obs) / self.cfg.sigma_r) ** 2)
            occl = np.where(
                rh > d_obs + self.cfg.r_safe,
                self.cfg.rho_occl * p_th,
                0.0,
            )

            local_risk[has_obs] = 1.0 - (1.0 - radial) * (1.0 - occl)

        risks[valid] = np.clip(local_risk, 0.0, 1.0)
        return risks

    def query_risk(self, point: np.ndarray) -> float:
        return float(self.query_risk_many(np.asarray(point))[0])


# ============================================================
# 3. Fast local 2D FMM-like arrival field
# ============================================================

@dataclass
class FMMConfig:
    x_min: float = -0.5
    x_max: float = 7.5
    y_min: float = -3.5
    y_max: float = 3.5
    resolution: float = 0.20

    # Cost = 1 + risk_alpha * risk.
    risk_alpha: float = 5.0

    # Treat very high-risk cells as blocked.
    obstacle_risk_block: float = 0.93


class FastLocalFMM2D:
    """
    Low-resolution local 2D FMM-like arrival field.

    This is Dijkstra-style ordered propagation on a risk-weighted grid.
    It is used as a fast approximation of FMM for local guidance.
    """

    def __init__(self, cfg: FMMConfig):
        self.cfg = cfg

        self.xs = np.arange(cfg.x_min, cfg.x_max + 1e-9, cfg.resolution)
        self.ys = np.arange(cfg.y_min, cfg.y_max + 1e-9, cfg.resolution)

        self.nx = len(self.xs)
        self.ny = len(self.ys)

        self.risk_grid = np.zeros((self.ny, self.nx), dtype=float)
        self.cost_grid = np.ones((self.ny, self.nx), dtype=float)
        self.T = np.full((self.ny, self.nx), np.inf, dtype=float)

    def world_to_idx(self, p_xy: np.ndarray) -> Tuple[int, int]:
        x, y = float(p_xy[0]), float(p_xy[1])

        ix = int(round((x - self.cfg.x_min) / self.cfg.resolution))
        iy = int(round((y - self.cfg.y_min) / self.cfg.resolution))

        ix = int(np.clip(ix, 0, self.nx - 1))
        iy = int(np.clip(iy, 0, self.ny - 1))

        return iy, ix

    def idx_to_world(self, iy: int, ix: int) -> np.ndarray:
        return np.array([self.xs[ix], self.ys[iy]], dtype=float)

    def build_risk_grid(self, field: SectorThreatField, z_slice: float = 0.0) -> None:
        xx, yy = np.meshgrid(self.xs, self.ys)
        pts = np.stack(
            [xx.ravel(), yy.ravel(), np.full(xx.size, z_slice)],
            axis=1,
        )

        risks = field.query_risk_many(pts)
        self.risk_grid = risks.reshape(self.ny, self.nx)

        self.cost_grid = 1.0 + self.cfg.risk_alpha * self.risk_grid
        self.cost_grid[self.risk_grid >= self.cfg.obstacle_risk_block] = np.inf

    def compute_arrival_from_goal(self, goal_xy: np.ndarray) -> None:
        """
        Propagate arrival time from known local target position.
        """
        self.T.fill(np.inf)

        gy, gx = self.world_to_idx(goal_xy)
        self.T[gy, gx] = 0.0

        pq = [(0.0, gy, gx)]

        neighbors = [
            (-1, 0, 1.0), (1, 0, 1.0), (0, -1, 1.0), (0, 1, 1.0),
            (-1, -1, np.sqrt(2)), (-1, 1, np.sqrt(2)),
            (1, -1, np.sqrt(2)), (1, 1, np.sqrt(2)),
        ]

        while pq:
            t, iy, ix = heapq.heappop(pq)

            if t != self.T[iy, ix]:
                continue

            for dy, dx, dist_mul in neighbors:
                jy = iy + dy
                jx = ix + dx

                if jy < 0 or jy >= self.ny or jx < 0 or jx >= self.nx:
                    continue

                if not np.isfinite(self.cost_grid[jy, jx]):
                    continue

                edge_cost = 0.5 * (self.cost_grid[iy, ix] + self.cost_grid[jy, jx])
                nt = t + edge_cost * self.cfg.resolution * dist_mul

                if nt < self.T[jy, jx]:
                    self.T[jy, jx] = nt
                    heapq.heappush(pq, (nt, jy, jx))

    def query_T(self, p_xy: np.ndarray) -> float:
        iy, ix = self.world_to_idx(p_xy)
        return float(self.T[iy, ix])

    def query_grid_risk(self, p_xy: np.ndarray) -> float:
        iy, ix = self.world_to_idx(p_xy)
        return float(self.risk_grid[iy, ix])

    def query_line_risk_grid(self, p0: np.ndarray, p1: np.ndarray, n_samples: int = 8) -> float:
        p0 = np.asarray(p0, dtype=float)
        p1 = np.asarray(p1, dtype=float)

        risks = []
        for i in range(n_samples):
            alpha = (i + 1) / n_samples
            q = (1 - alpha) * p0 + alpha * p1
            risks.append(self.query_grid_risk(q[:2]))

        risks = np.asarray(risks, dtype=float)

        return float(0.7 * np.max(risks) + 0.3 * np.mean(risks))

    def query_descent_score(self, current_xy: np.ndarray, candidate_xy: np.ndarray, step_len: float) -> float:
        """
        Positive when candidate moves toward lower arrival time.
        """
        Tc = self.query_T(current_xy)
        Tn = self.query_T(candidate_xy)

        if not np.isfinite(Tc) or not np.isfinite(Tn):
            return -1.0

        return float((Tc - Tn) / max(step_len, 1e-6))


# ============================================================
# 4. Known-goal sequence generation
# ============================================================

@dataclass
class SequenceGeneratorConfig:
    k_waypoints: int = 9
    step_len: float = 0.65

    cone_angle_deg: float = 75.0
    top_k: int = 32

    line_samples: int = 8

    # Top-k candidate score:
    # score = goal alignment - risk + FMM descent
    topk_w_goal: float = 0.8
    topk_w_point_risk: float = 1.3
    topk_w_line_risk: float = 2.5
    topk_w_fmm: float = 1.0

    # Final candidate cost:
    # lower is better.
    cost_w_point_risk: float = 2.5
    cost_w_line_risk: float = 5.5
    cost_w_goal: float = 0.7
    cost_w_smooth: float = 0.25
    cost_w_height: float = 0.15
    cost_w_progress: float = 0.25
    cost_w_fmm: float = 1.0

    # Stop early if close to known goal.
    goal_tolerance: float = 0.45


class KnownGoalGuidingSequenceGenerator:
    """
    Generate a local guiding waypoint sequence toward a known target.

    This performs a virtual rollout in the local frame.
    It does not imply the robot actually follows or replans at each point.
    """

    def __init__(
        self,
        field: SectorThreatField,
        fmm: FastLocalFMM2D,
        cfg: SequenceGeneratorConfig,
    ):
        self.field = field
        self.fmm = fmm
        self.cfg = cfg

    def _candidate_dirs(self, virtual_pos: np.ndarray, goal_dir: np.ndarray) -> np.ndarray:
        dirs = self.field.sector_dirs.reshape(-1, 3)
        goal_dir = normalize(goal_dir)

        goal_scores = dirs @ goal_dir
        cos_th = np.cos(np.deg2rad(self.cfg.cone_angle_deg))

        mask = goal_scores >= cos_th
        cand_dirs = dirs[mask]
        cand_goal_scores = goal_scores[mask]

        if len(cand_dirs) == 0:
            idx = np.argsort(goal_scores)[::-1][:self.cfg.top_k]
            return dirs[idx]

        scores = np.zeros(len(cand_dirs), dtype=float)

        for i, (d, gs) in enumerate(zip(cand_dirs, cand_goal_scores)):
            d = normalize(d)
            candidate = virtual_pos + self.cfg.step_len * d

            point_risk = self.fmm.query_grid_risk(candidate[:2])
            line_risk = self.fmm.query_line_risk_grid(
                virtual_pos,
                candidate,
                n_samples=self.cfg.line_samples,
            )
            fmm_score = self.fmm.query_descent_score(
                virtual_pos[:2],
                candidate[:2],
                self.cfg.step_len,
            )

            scores[i] = (
                self.cfg.topk_w_goal * gs
                - self.cfg.topk_w_point_risk * point_risk
                - self.cfg.topk_w_line_risk * line_risk
                + self.cfg.topk_w_fmm * fmm_score
            )

        if len(cand_dirs) > self.cfg.top_k:
            idx = np.argsort(scores)[::-1][:self.cfg.top_k]
            cand_dirs = cand_dirs[idx]

        return cand_dirs

    def generate(self, start_pos: np.ndarray, goal_pos: np.ndarray):
        waypoints = []
        generation_times_ms = []
        candidate_counts = []
        selected_costs = []

        virtual_pos = start_pos.astype(float).copy()
        prev_dir = normalize(goal_pos - start_pos)

        for _ in range(self.cfg.k_waypoints):
            if np.linalg.norm(goal_pos - virtual_pos) <= self.cfg.goal_tolerance:
                break

            t0 = time.perf_counter()

            goal_dir = normalize(goal_pos - virtual_pos)
            candidate_dirs = self._candidate_dirs(virtual_pos, goal_dir)

            best_cost = np.inf
            best_point = None
            best_dir = None

            for d in candidate_dirs:
                d = normalize(d)
                candidate = virtual_pos + self.cfg.step_len * d

                point_risk = self.fmm.query_grid_risk(candidate[:2])
                line_risk = self.fmm.query_line_risk_grid(
                    virtual_pos,
                    candidate,
                    n_samples=self.cfg.line_samples,
                )

                goal_cost = 1.0 - np.dot(d, goal_dir)
                smooth_cost = 1.0 - np.dot(d, prev_dir)
                height_cost = abs(candidate[2] - virtual_pos[2])
                progress = np.linalg.norm(virtual_pos - goal_pos) - np.linalg.norm(candidate - goal_pos)
                fmm_score = self.fmm.query_descent_score(
                    virtual_pos[:2],
                    candidate[:2],
                    self.cfg.step_len,
                )

                cost = (
                    self.cfg.cost_w_point_risk * point_risk
                    + self.cfg.cost_w_line_risk * line_risk
                    + self.cfg.cost_w_goal * goal_cost
                    + self.cfg.cost_w_smooth * smooth_cost
                    + self.cfg.cost_w_height * height_cost
                    - self.cfg.cost_w_progress * progress
                    - self.cfg.cost_w_fmm * fmm_score
                )

                if cost < best_cost:
                    best_cost = cost
                    best_point = candidate
                    best_dir = d

            if best_point is None:
                best_dir = goal_dir
                best_point = virtual_pos + self.cfg.step_len * best_dir
                best_cost = np.nan

            waypoints.append(best_point)
            selected_costs.append(float(best_cost))
            candidate_counts.append(len(candidate_dirs))
            generation_times_ms.append((time.perf_counter() - t0) * 1000.0)

            # Virtual rollout only: generate sequence, not actual robot motion.
            virtual_pos = best_point
            prev_dir = best_dir

        return (
            np.asarray(waypoints, dtype=float),
            generation_times_ms,
            candidate_counts,
            selected_costs,
        )


# ============================================================
# 5. Visualization
# ============================================================

def visualize(
    fmm: FastLocalFMM2D,
    lidar_points: np.ndarray,
    start_pos: np.ndarray,
    goal_pos: np.ndarray,
    waypoints: np.ndarray,
    cylinder_center: np.ndarray,
    cylinder_radius: float,
) -> None:
    # 2D risk + FMM arrival contours
    fig = plt.figure(figsize=(8, 6))
    ax = fig.add_subplot(111)

    im = ax.contourf(fmm.xs, fmm.ys, fmm.risk_grid, levels=30)
    plt.colorbar(im, ax=ax, label="risk")

    finite_T = np.where(np.isfinite(fmm.T), fmm.T, np.nan)
    try:
        ax.contour(fmm.xs, fmm.ys, finite_T, levels=18, linewidths=0.6, alpha=0.65)
    except Exception:
        pass

    circle = plt.Circle(
        (cylinder_center[0], cylinder_center[1]),
        cylinder_radius,
        fill=False,
        linewidth=2,
    )
    ax.add_patch(circle)

    ax.scatter(start_pos[0], start_pos[1], marker="o", s=80, label="start/current")
    ax.scatter(goal_pos[0], goal_pos[1], marker="*", s=140, label="known goal")

    if len(waypoints) > 0:
        ax.plot(
            waypoints[:, 0],
            waypoints[:, 1],
            marker="o",
            linewidth=2,
            label="generated guiding sequence",
        )

    ax.set_title("Known-goal local FMM-like guiding sequence")
    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_aspect("equal")
    ax.legend()
    plt.tight_layout()
    plt.show()

    # 3D LiDAR + guiding sequence
    fig = plt.figure(figsize=(8, 6))
    ax = fig.add_subplot(111, projection="3d")

    sample_n = min(1400, len(lidar_points))
    idx = np.random.choice(len(lidar_points), sample_n, replace=False)
    pts = lidar_points[idx]

    ax.scatter(pts[:, 0], pts[:, 1], pts[:, 2], s=2, alpha=0.25, label="current LiDAR points")
    ax.scatter(start_pos[0], start_pos[1], start_pos[2], marker="o", s=90, label="start/current")
    ax.scatter(goal_pos[0], goal_pos[1], goal_pos[2], marker="*", s=160, label="known goal")

    if len(waypoints) > 0:
        ax.plot(
            waypoints[:, 0],
            waypoints[:, 1],
            waypoints[:, 2],
            marker="o",
            linewidth=2,
            label="guiding sequence",
        )

    ax.set_title("3D current LiDAR observation and generated guiding sequence")
    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_zlabel("z [m]")
    ax.set_xlim(-0.5, 7.2)
    ax.set_ylim(-3.2, 3.2)
    ax.set_zlim(-1.8, 1.8)
    ax.legend()
    plt.tight_layout()
    plt.show()


# ============================================================
# 6. Main demo
# ============================================================

def main() -> None:
    np.random.seed(7)

    start_pos = np.array([0.0, 0.0, 0.0])
    known_goal_pos = np.array([7.0, 0.0, 0.0])

    # Simulated current local LiDAR observation.
    cylinder_center = np.array([3.2, 0.0, 0.0])
    cylinder_radius = 0.75
    cylinder_height = 2.5

    lidar_points = generate_cylinder_surface_points(
        center=cylinder_center,
        radius=cylinder_radius,
        height=cylinder_height,
        n_theta=180,
        n_z=90,
    )
    lidar_points = lidar_points + np.random.normal(scale=0.015, size=lidar_points.shape)

    sector_cfg = SectorThreatConfig(
        n_theta=36,
        n_phi=13,
        r_max=8.0,
        lidar_phi_min=np.deg2rad(-45),
        lidar_phi_max=np.deg2rad(45),
        r_safe=0.45,
        sigma_d=0.9,
        sigma_r=0.5,
        density_alpha=0.06,
        rho_occl=0.6,
    )

    fmm_cfg = FMMConfig(
        x_min=-0.5,
        x_max=7.5,
        y_min=-3.5,
        y_max=3.5,
        resolution=0.20,
        risk_alpha=5.0,
        obstacle_risk_block=0.93,
    )

    seq_cfg = SequenceGeneratorConfig(
        k_waypoints=9,
        step_len=0.65,
        cone_angle_deg=75,
        top_k=32,
        line_samples=8,
        topk_w_goal=0.8,
        topk_w_point_risk=1.3,
        topk_w_line_risk=2.5,
        topk_w_fmm=1.0,
        cost_w_point_risk=2.5,
        cost_w_line_risk=5.5,
        cost_w_goal=0.7,
        cost_w_smooth=0.25,
        cost_w_height=0.15,
        cost_w_progress=0.25,
        cost_w_fmm=1.0,
        goal_tolerance=0.45,
    )

    t_total_start = time.perf_counter()

    t0 = time.perf_counter()
    field = SectorThreatField(sector_cfg)
    field.build_from_lidar_points(lidar_points)
    sector_time_ms = (time.perf_counter() - t0) * 1000.0

    t0 = time.perf_counter()
    fmm = FastLocalFMM2D(fmm_cfg)
    fmm.build_risk_grid(field, z_slice=0.0)
    risk_grid_time_ms = (time.perf_counter() - t0) * 1000.0

    t0 = time.perf_counter()
    fmm.compute_arrival_from_goal(known_goal_pos[:2])
    fmm_time_ms = (time.perf_counter() - t0) * 1000.0

    t0 = time.perf_counter()
    generator = KnownGoalGuidingSequenceGenerator(
        field=field,
        fmm=fmm,
        cfg=seq_cfg,
    )
    waypoints, gen_times_ms, cand_counts, costs = generator.generate(
        start_pos=start_pos,
        goal_pos=known_goal_pos,
    )
    sequence_time_ms = (time.perf_counter() - t0) * 1000.0

    total_time_ms = (time.perf_counter() - t_total_start) * 1000.0

    visualize(
        fmm=fmm,
        lidar_points=lidar_points,
        start_pos=start_pos,
        goal_pos=known_goal_pos,
        waypoints=waypoints,
        cylinder_center=cylinder_center,
        cylinder_radius=cylinder_radius,
    )

    print("=== Known-goal local guiding sequence timing ===")
    print(f"Sector threat build:       {sector_time_ms:.3f} ms")
    print(f"Risk grid build:           {risk_grid_time_ms:.3f} ms")
    print(f"FMM-like propagation:      {fmm_time_ms:.3f} ms")
    print(f"Sequence generation:       {sequence_time_ms:.3f} ms")
    print(f"Total flow:                {total_time_ms:.3f} ms")
    print(f"Grid shape:                {fmm.risk_grid.shape}, cells={fmm.risk_grid.size}")
    print(f"Top-k:                     {seq_cfg.top_k}")
    print(f"Cone angle:                {seq_cfg.cone_angle_deg} deg")
    print(f"Line risk samples:         {seq_cfg.line_samples}")
    print(f"Generated waypoint count:  {len(waypoints)}")
    print(f"Average candidates:        {np.mean(cand_counts):.1f}" if len(cand_counts) else "Average candidates:        N/A")
    print()

    print("=== Generated guiding sequence ===")
    for i, (wp, dt, cc, cst) in enumerate(zip(waypoints, gen_times_ms, cand_counts, costs), start=1):
        print(
            f"w{i}: [{wp[0]: .3f}, {wp[1]: .3f}, {wp[2]: .3f}], "
            f"risk={fmm.query_grid_risk(wp[:2]):.3f}, "
            f"T={fmm.query_T(wp[:2]):.3f}, "
            f"candidates={cc}, cost={cst:.3f}, generation_time={dt:.3f} ms"
        )


if __name__ == "__main__":
    main()
